CREATE DATABASE BookstoreDB;
USE BookstoreDB;

CREATE TABLE PUBLISHER (
    Name VARCHAR(100) PRIMARY KEY
);

CREATE TABLE BOOK (
    ISBN VARCHAR(20) PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Category VARCHAR(50),
    PublicationYear INT,
    SellingPrice DECIMAL(10, 2) NOT NULL CHECK (SellingPrice >= 0),
    Threshold INT NOT NULL DEFAULT 5 CHECK (Threshold >= 0),
    StockQuantity INT NOT NULL DEFAULT 0 CHECK (StockQuantity >= 0),
    PublisherName VARCHAR(100),
    CONSTRAINT chk_category CHECK (Category IN ('Science', 'Art', 'Religion', 'History', 'Geography')),
    FOREIGN KEY (PublisherName) REFERENCES PUBLISHER(Name) ON UPDATE CASCADE
);

CREATE TABLE CUSTOMER (
    Username VARCHAR(50) PRIMARY KEY,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(10) NOT NULL DEFAULT 'customer',
    CONSTRAINT chk_role CHECK (Role IN ('customer', 'admin')),
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Email VARCHAR(100) UNIQUE,
    Phone VARCHAR(20),
    ShippingAddress VARCHAR(255)
);

CREATE TABLE CUSTOMER_ORDER (
    OrderNo INT AUTO_INCREMENT PRIMARY KEY,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    TotalPrice DECIMAL(10, 2),
    CustomerUsername VARCHAR(50),
    FOREIGN KEY (CustomerUsername) REFERENCES CUSTOMER(Username) ON UPDATE CASCADE
);

CREATE TABLE ORDER_ITEMS (
    OrderNo INT,
    ISBN VARCHAR(20),
    Quantity INT NOT NULL CHECK (Quantity > 0),
    UnitPrice DECIMAL(10, 2) NOT NULL CHECK (UnitPrice >= 0),
    PRIMARY KEY (OrderNo, ISBN),
    FOREIGN KEY (OrderNo) REFERENCES CUSTOMER_ORDER(OrderNo) ON DELETE CASCADE,
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE
);

CREATE TABLE ADMIN_ORDER (
    RestockID INT AUTO_INCREMENT PRIMARY KEY,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    Status VARCHAR(20) DEFAULT 'Pending',
    ISBN VARCHAR(20),
    CONSTRAINT chk_status CHECK (Status IN ('Pending', 'Confirmed')),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE
);

CREATE TABLE BOOK_AUTHORS (
    ISBN VARCHAR(20),
    AuthorName VARCHAR(100),
    PRIMARY KEY (ISBN, AuthorName),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PUBLISHER_PHONES (
    PublisherName VARCHAR(100),
    PhoneNumber VARCHAR(20),
    PRIMARY KEY (PublisherName, PhoneNumber),
    FOREIGN KEY (PublisherName) REFERENCES PUBLISHER(Name) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PUBLISHER_ADDRESSES (
    PublisherName VARCHAR(100),
    Address VARCHAR(255),
    PRIMARY KEY (PublisherName, Address),
    FOREIGN KEY (PublisherName) REFERENCES PUBLISHER(Name) ON DELETE CASCADE ON UPDATE CASCADE
);